spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 2qordjr10@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform : org.hibernate.dialect.MySQL8Dialect
    profiles:
      active: local
  logging:
    output:
      ansi:
        enabled: always
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.sql.BasicBinder: TRACE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012
